modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "zerocontact"
version = "${version}"
displayName = "Zero Contact"
authors = "TuDouNi92"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.zerocontact]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zerocontact]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zerocontact]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.zerocontact]]
modId = "curios"
mandatory = true
versionRange = "[5.9.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zerocontact]]
modId = "tacz"
mandatory = true
versionRange = "[1.0.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zerocontact]]
modId = "geckolib"
mandatory = true
versionRange = "[4.2.1,)"
ordering = "NONE"
side = "BOTH"

