name: Build ZeroContact
on:
  push:
    branches: [main]
    tags:
      - 'indev.*.*.*'
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build for Forge
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name : Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Make Gradle Executable
        run: chmod +x ./gradlew
      - name: Build and Remap Jar
        run: ./gradlew :forge:remapJar
        
       
 
