name: NightlyBuild ZeroContact
on:
  schedule:
    - cron: '0 0 * * 1'
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build for Forge
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name : Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Make Gradle Executable
        run: chmod +x ./gradlew
      - name: Build and Remap Jar
        run: ./gradlew :forge:remapJar

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZeroContact-${{ github.ref_name }}-build-${{ github.run_number }}-${{steps.vars.outputs.SHORT_SHA}}
          path: forge/build/libs/zerocontact-*.*.*.jar

      - name: Rename file
        run: |
          mkdir -p nightly 
          original_jar=$(ls forge/build/libs/zerocontact-*.*.[0-9].jar) 
          new_jar="ZeroContact-${{ github.ref_name }}-build-${{ github.run_number }}-${{steps.vars.outputs.SHORT_SHA}}.jar" 
          cp "$original_jar" "nightly/$new_jar" 

      - name: Upload to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEB_HOOK }}
          filename: "nightly/ZeroContact-${{ github.ref_name }}-build-${{ github.run_number }}-${{steps.vars.outputs.SHORT_SHA}}.jar"

